language: bash


before_install:
  - sudo apt-get update && sudo apt-get install -y shellcheck

script:
        - ls -l
        - bash task3.sh
        - ls -l
        - pwd

notifications:
  email:
    on_success: never

